### ISSUE TITLE
Add "Thanks!" button

### ISSUE THREAD

**Issue by ErikBjare** [SuperuserLabs/thankful#1]
Handing out "thanks" manually could be a great aid in marking which content one really enjoys (and wants to thank for), doing it manually also acts as a way to "favorite" content while browsing.

Possible solutions:

 - Turn web extension icon/popup into a Thanks-button
 - Import likes/favorites/stars (from e.g. YouTube, GitHub)
 - Thanks button next to like/dislike buttons on YouTube

**Comment by Powersource** [comment]
We have a Thanks button in the popup since https://github.com/SuperuserLabs/thankful/pull/66 so I made separate issues for the other options: https://github.com/SuperuserLabs/thankful/issues/110, https://github.com/SuperuserLabs/thankful/issues/111.
