### ISSUE TITLE
Investigate improving load times

### ISSUE THREAD

**Issue by Powersource** [SuperuserLabs/thankful#119]
Sitting on 51216b8 right now and the popup takes almost 2 seconds to open and the dashboard takes at least 3. 0.4.2 is a lot faster (even if it's still pretty slow), is the difference because of dev vs. prod or is it because of recent changes? In any case, how can we improve load times?

**Comment by ErikBjare** [comment]
It's fast enough on my machine (Chromium), does anyone else have this issue?

**Comment by Powersource** [comment]
@johan-bjareholt How is it in Firefox for you?
@patrik-laurell How is it on your super fast computer?

**Comment by johan-bjareholt** [comment]
It was instantaneous for me before, but it seems to take about 2 seconds for me as well now.

**Comment by vlthr** [comment]
On my laptop (using chromium) it takes about half a second for the popup to be raised, and about one second for the dashboard to render.

**Comment by ahnlabb** [comment]
@johan-bjareholt, @Powersource , please test #123 (specifically 57d4cfe45faa82292e3eca4fbe3e023567b7d3fd). I've made a few optimizations and also fixed a major bug where all activities without a creator were loaded and sorted despite never being shown (a couple of 100 ms wasted on that on my computer). These optimizations halved the loading time for me and I'd like to know how it affects yours.

**Comment by Powersource** [comment]
The dashboard loading time is ok now with https://github.com/SuperuserLabs/thankful/pull/123, but the popup is a lot slower than in 0.4.2.
