### ISSUE TITLE
How to make transactions?

### ISSUE THREAD

**Issue by ErikBjare** [SuperuserLabs/thankful#12]
## Problem

We thought we could use MetaMask from the extension, but apparently, you can't use the MetaMask provider from a web extension.

## Solutions

 - Create raw transactions, ask people to sign and send them using MyEtherWallet
 - Create a wallet in Thankful
   - Con: Complex?
 - Build a payment gateway
   - Have an API that takes as input (creator/addresses -> amount) mappings, signs and sends transactions.
   - Con: The simplest version would require us to keep a private key/wallet for users.
 - Create a gateway that only interacts with MetaMask
   - Con: Likely security problems

## Research to do

 - How does Web3 work in more detail, what are the capabilities? What does providers actually provide?

(Discussed with @Powersource)

**Comment by Powersource** [comment]
Metamask actually seems to have solved this problem recently, it just isn't documented yet. https://github.com/MetaMask/metamask-extension/issues/4577  
As mentioned there, until they pull the needed files into a separate module we'll have to import the entirety of Metamask as a dependency (:sweat_smile:) but at least it should work.

**Comment by ErikBjare** [comment]
Omg, that's amazing! Full steam ahead! 🚂 :rocket:

**Comment by Powersource** [comment]
It woooorks :D https://github.com/SuperuserLabs/thankful/commit/a17818af804b0eb12cb16e375ee90ca173c54eb9
