### ISSUE TITLE
Display Thanks amounts in activity listings

### ISSUE THREAD

**Issue by Powersource** [SuperuserLabs/thankful#124]
This is probably gonna require some clever manual db joining to not get super slow.

The amounts should both be shown in the All activity page but also in the activity cards for individual creators (when that gets added).

**Comment by ErikBjare** [comment]
Fixed in https://github.com/SuperuserLabs/thankful/pull/205, also https://github.com/SuperuserLabs/thankful/pull/210 for the creator listing.
