### ISSUE TITLE
Consider using ethjs instead web3.js to get promises

### ISSUE THREAD

**Issue by Powersource** [SuperuserLabs/thankful#13]
The web3.js api is based on callbacks which might get messy in the future. (well it has ["PromiEvents"](https://web3js.readthedocs.io/en/1.0/callbacks-promises-events.html) but they don't really count)

Ethjs example https://github.com/ethjs/ethjs/blob/master/docs/user-guide.md#ethaccounts

**Comment by ErikBjare** [comment]
Won't happen
