### ISSUE TITLE
Content scripts run into <unavailable> Firefox bug

### ISSUE THREAD

**Issue by Powersource** [SuperuserLabs/thankful#151]
Can't attach youtube creators suddenly https://bugzilla.mozilla.org/show_bug.cgi?id=1136995

**Comment by ErikBjare** [comment]
Wasn't this (partially?) fixed?

**Comment by Powersource** [comment]
Yeah apparently it only prints like this in the extension debug console, works fine in the page the content script is running.

**Comment by Powersource** [comment]
The bug I thought was this was something else and is fixed here https://github.com/SuperuserLabs/thankful/pull/152
