### ISSUE TITLE
Figure out the best way to unit test donations

### ISSUE THREAD

**Issue by Powersource** [SuperuserLabs/thankful#16]
Is there any option where the tests don't need the chain to confirm? (i.e. the tests take < 30 seconds)

Truffle seems to have a [testing framework](http://truffleframework.com/docs/getting_started/javascript-tests), not sure how slow it is, and it seems pretty focused on contracts as well but it might work.

**Comment by ErikBjare** [comment]
Unit testing donations seems too difficult to be practical, closing for now.
