### ISSUE TITLE
Fix deterministic builds

### ISSUE THREAD

**Issue by Powersource** [SuperuserLabs/thankful#161]
Getting emails from mozilla saying they get a differing xpi when building, compared to the extension we uploaded. This is hopefully just from a combination of
* Me generating the source zip locally, potentially using a slightly modified package-lock. (my laptop doesn't seem to like prebuilt keccak and switches to keccakjs). We should just grab the src zip from the release page on github.
* Me telling them to build using `make build` instead of `make build-production`. We should just tell them do do `make prepublish`.

but my testing and diffing suggests there's something more.

**Comment by ErikBjare** [comment]
We should just make a new release with the right instructions and the releases zip. That should do the trick.

**Comment by Powersource** [comment]
That's hoping mozilla's build environment is the same as Travis's, but yes worth a shot.

**Comment by Powersource** [comment]
Might have been fixed by https://github.com/SuperuserLabs/thankful/pull/170, we'll have to see what the mozilla reviewer says about 0.6.5.

**Comment by Powersource** [comment]
Nope, didn't work, even after I told them to use npm ci.

**Comment by Powersource** [comment]
Asked them to provide their build log.

**Comment by Powersource** [comment]
And we're back on AMO since a few days ago :tada:
