### ISSUE TITLE
remove Gratipay from Readme

### ISSUE THREAD

**Issue by wolftune** [SuperuserLabs/thankful#188]
Gratipay is defunct.

Incidentally, if you want a list of much more of the ways to fund free culture, see https://wiki.snowdrift.coop/market-research/other-crowdfunding (my platform-in-progress's much more thorough research on the whole market)

P.S. You're doing it right by combining the metrics with the *choice* of who to fund rather than the obnoxious assumption some attempts make where they want to automatically tie funding to attention even when you *regret* that use of your attention.

**Comment by ErikBjare** [comment]
Excellent writeup! Would love to have a chat about your general thoughts on the market sometime, as we're very much committed to making this work for all types of content, and see ourselves becoming much more than just a tipping service.

**Comment by wolftune** [comment]
@ErikBjare if you want my perspective, you can read through the rest of the Snowdrift.coop wiki stuff, as it's even more efficient than what I can say off the top of my head. But if you have specific questions or want to otherwise share perspectives, I'm happy to do that. Obviously if the solutions to our economic dilemmas were simple and easy, they'd already be solved. Half the challenge is changing the conversation to where people are getting the diagnoses correct.

**Comment by ErikBjare** [comment]
This was closed as we moved the list of alternatives to [the wiki](https://github.com/SuperuserLabs/thankful/wiki/Alternatives) (also includes a link to @wolftune's research).

**Comment by wolftune** [comment]
The wiki ought to mention that Gratipay is defunct (perhaps parentheses after the listing). I can't edit the wiki or make pull-requests or anything. As it is set, the wiki is only writable by project members, so it's not open to contributions from outside.
