### ISSUE TITLE
Publish to Chrome Web Store and Mozilla Add-ons

### ISSUE THREAD

**Issue by Powersource** [SuperuserLabs/thankful#30]
WIP branch here https://github.com/SuperuserLabs/thankful/tree/dev/publish

https://developer.mozilla.org/en-US/Add-ons/Distribution/Submitting_an_add-on#Listing_on_AMO
https://developer.chrome.com/webstore/publish

**Comment by ErikBjare** [comment]
The basic publishing is done, see https://github.com/SuperuserLabs/thankful/pull/32
