### ISSUE TITLE
Don't log in private browsing

### ISSUE THREAD

**Issue by Powersource** [SuperuserLabs/thankful#35]
Seems we only need to set this manifest variable https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/incognito to `not_allowed`.

**Comment by ErikBjare** [comment]
This might be an interesting read for you, apparently the `incognito: not_allowed` isn't reliable: https://github.com/ActivityWatch/aw-watcher-web/pull/18

**Comment by johan-bjareholt** [comment]
Seems like Firefox has an architectural issue with disabling extensions per-window:
https://bugzilla.mozilla.org/show_bug.cgi?id=822675

Not sure if we should even attempt to fix this properly.
You can't access localstorage in icognito either.

Should I still keep #50 or should we reject it?

**Comment by Powersource** [comment]
I seems you can access localstorage somehow, it manages to log for me. The background script might be able to?
