### ISSUE TITLE
Description and screenshots at addons.mozilla.org (AMO) and Chrome Webstore

### ISSUE THREAD

**Issue by grahamperrin** [SuperuserLabs/thankful#37]
Re: #30 

https://addons.mozilla.org/addon/getthankful/ please, can you add some screenshots, and be more descriptive? 

Help potential users decide whether to install the extension.

**Comment by johan-bjareholt** [comment]
Sorry for the late reply.

The extension is still in early development and we are doing lots of UI changes currently, so there's little point in supplying screenshots currently. I'll keep this issue though because we will do this eventually!

**Comment by Powersource** [comment]
Waiting on https://github.com/SuperuserLabs/thankful/issues/146

**Comment by Powersource** [comment]
Screenshots fixed for both AMO and webstore, only descriptions are needed now (i.e. we're not waiting on #146 anymore).
