### ISSUE TITLE
Records activity even if computer is idle/suspended?

### ISSUE THREAD

**Issue by johan-bjareholt** [SuperuserLabs/thankful#61]
I am very certain that I have not spent 60+ hours on the top 3 websites here

![thankful bug](https://user-images.githubusercontent.com/1398500/42439858-50c64982-8364-11e8-8ff9-a6376d9dabc6.png)

**Comment by ErikBjare** [comment]
This should be fixable if the computer is idle/suspended by adding a few checks to `background.js`.

But it probably also occurs when the browser window is open but not active, and for this I can't seem to figure out a fix...

**Comment by ErikBjare** [comment]
I think this was mostly or entirely fixed by https://github.com/SuperuserLabs/thankful/pull/67. Closing.
