### ISSUE TITLE
Use "Thanks"

### ISSUE THREAD

**Issue by Powersource** [SuperuserLabs/thankful#95]
Right now users can click "Thanks" in the popup but it has no real effect.

I'm thinking so far we'll just include it in the $ distribution heuristic in some simple way. Simplest is to make it count as ~1 hour, but from feedback it might make more sense to make it equal some fixed amount of $.

**Comment by ErikBjare** [comment]
One thing I'm considering is a simple form "You thanked creators `x` times the last `n` days, how much do you want to send to each/in total?"
